Pilot/Models/ErrorViewModel.cs
using System;

namespace Pilot.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Pilot/Models/Lyric.cs
namespace Pilot.Models
{
    public class Lyric
    {
        public int Milliseconds { get; set; }
        public string Text { get; set; }

        public Lyric(int milliseconds, string text)
        {
            Milliseconds = milliseconds;
            Text = text;
        }
    }
}

Pilot/Models/SongInfo.cs
namespace Pilot.Models
{
    public class SongInfo
    {
        public string Title { get; set; }
        public string Artist { get; set; }
        public string Album { get; set; }
        public byte[] Image { get; set; }
        public string ImageMimeType { get; set; }
        public int Length { get; set; }
        public int CurrentPosition { get; set; }
        public string Path { get; internal set; }
        public uint? Track { get; internal set; }
        public uint? Year { get; internal set; }
        public string Genere { get; internal set; }
        public Lyric[] Lyrics { get; set; }
    }
}

Pilot/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Pilot.Models;

namespace Pilot.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return RedirectToAction("Index", "PilotLocal");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pilot/Controllers/PilotController.cs
using Microsoft.AspNetCore.Mvc;
using Pilot.Logic.Managers;
using Pilot.Logic.WinKeys;

namespace Pilot.Controllers
{
    public class PilotController : Controller
    {
        private readonly KeyEventsManager keyEventsManager;

        public PilotController(KeyEventsManager keyEventsManager)
        {
            this.keyEventsManager = keyEventsManager;
        }

        public IActionResult LaunchMedia()
        {
            keyEventsManager.SendKeyEvent(KeyCode.LAUNCH_MEDIA_SELECT);
            return Json(true);
        }

        public IActionResult Play()
        {
            keyEventsManager.SendKeyEvent(KeyCode.MEDIA_PLAY_PAUSE);
            return Json(true);
        }

        public IActionResult Previous()
        {
            keyEventsManager.SendKeyEvent(KeyCode.MEDIA_PREV_TRACK);
            return Json(true);
        }

        public IActionResult Next()
        {
            keyEventsManager.SendKeyEvent(KeyCode.MEDIA_NEXT_TRACK);
            return Json(true);
        }

        public IActionResult Stop()
        {
            keyEventsManager.SendKeyEvent(KeyCode.MEDIA_STOP);
            return Json(true);
        }

        public IActionResult Info()
        {
            return Json(SongManager.Instance.CurrentSong);
        }

        public IActionResult Image()
        {
            return File(SongManager.Instance.CurrentSong.Image, SongManager.Instance.CurrentSong.ImageMimeType);
        }
    }
}

Pilot/Controllers/PilotLocalController.cs
using Microsoft.AspNetCore.Mvc;
using Pilot.Logic.Managers;
using Pilot.Logic.WinKeys;

namespace Pilot.Controllers
{
    public class PilotLocalController : Controller
    {
        private readonly KeyEventsManager keyEventsManager;

        public PilotLocalController(KeyEventsManager keyEventsManager)
        {
            this.keyEventsManager = keyEventsManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LaunchMedia()
        {
            keyEventsManager.SendKeyEvent(KeyCode.LAUNCH_MEDIA_SELECT);
            return Json(true);
        }

        public IActionResult Play()
        {
            keyEventsManager.SendKeyEvent(KeyCode.MEDIA_PLAY_PAUSE);
            return Json(true);
        }

        public IActionResult Previous()
        {
            keyEventsManager.SendKeyEvent(KeyCode.MEDIA_PREV_TRACK);
            return Json(true);
        }

        public IActionResult Next()
        {
            keyEventsManager.SendKeyEvent(KeyCode.MEDIA_NEXT_TRACK);
            return Json(true);
        }

        public IActionResult Stop()
        {
            keyEventsManager.SendKeyEvent(KeyCode.MEDIA_STOP);
            return Json(true);
        }

        public IActionResult Info()
        {
            return Json(SongManager.Instance.CurrentSong);
        }

        public IActionResult Image()
        {
            return File(SongManager.Instance.CurrentSong.Image, SongManager.Instance.CurrentSong.ImageMimeType);
        }
    }
}

Pilot/Controllers/QrCodeController.cs
using Microsoft.AspNetCore.Mvc;
using Pilot.Logic.Managers;

namespace Pilot.Controllers
{
    public class QrCodeController : Controller
    {
        private readonly QrCodeManager qrCodeManager;

        public QrCodeController(QrCodeManager qrCodeManager)
        {
            this.qrCodeManager = qrCodeManager;
        }
        
        [ResponseCache(Duration = int.MaxValue)]
        public IActionResult SiteUrl()
        {
            var (content, mimeType) = qrCodeManager.GetSiteUrlQrCode();
            return File(content, mimeType);
        }
    }
}

Pilot/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pilot medialny";
}

<div class="container">
    <div class="row">&nbsp;</div>
    <div class="col-sm-12 col-md-4 col-lg-3">
        <img id="songImage" class="media-object" style="width: 250px; height: 250px;" src="" />
        <div class="row">&nbsp;</div>
    </div>
    <div class="col-sm-12 col-md-8 col-lg-9">
        <div class="input-group row">
            <span id="songTrackAddon" class="input-group-addon">Ścieżka</span>
            <input type="text" readonly class="form-control" id="songTrack" aria-describedby="songTrackAddon" value="">
        </div>
        <div class="input-group row">
            <span id="songTitleAddon" class="input-group-addon">Tytuł</span>
            <input type="text" readonly class="form-control" id="songTitle" aria-describedby="songTitleAddon" value="">
        </div>
        <div class="input-group row">
            <span id="songArtistAddon" class="input-group-addon">Wykonawca</span>
            <input type="text" readonly class="form-control" id="songArtist" aria-describedby="songArtistAddon" value="">
        </div>
        <div class="input-group row">
            <span id="songAlbumAddon" class="input-group-addon">Album</span>
            <input type="text" readonly class="form-control" id="songAlbum" aria-describedby="songAlbumAddon" value="">
        </div>
        <div class="input-group row">
            <span id="songYearAddon" class="input-group-addon">Rok</span>
            <input type="text" readonly class="form-control" id="songYear" aria-describedby="songYearAddon" value="">
        </div>
        <div class="input-group row">
            <span id="songGenereAddon" class="input-group-addon">Gatunek</span>
            <input type="text" readonly class="form-control" id="songGenere" aria-describedby="songGenereAddon" value="">
        </div>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <div id="songTime" class="pull-right"></div>
    </div>
    <div class="row">
        <div class="progress">
            <div id="songProgress" class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%; transition:2000ms;">
                <span class="sr-only">45% Complete</span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <button id="mediaButton" class="btn btn-default"><i class="fa fa-music"></i></button>
            <button id="playButton" class="btn btn-default"><i class="fa fa-play"></i> / <i class="fa fa-pause"></i></button>
            <button id="prevButton" class="btn btn-default"><i class="fa fa-backward"></i></button>
            <button id="nextButton" class="btn btn-default"><i class="fa fa-forward"></i></button>
            <button id="stopButton" class="btn btn-default"><i class="fa fa-stop"></i></button>
            <button id="infoButton" class="btn btn-default"><i class="glyphicon glyphicon-refresh"></i></button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <img id="qrCodeSiteUrl" class="media-object img-responsive center-block"
                 src="@Url.Action("SiteUrl", "QrCode")" />
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/pilot.js"></script>
}

Pilot/Views/Home/PilotYT.cshtml
@{
    ViewData["Title"] = "PilotYT";
}

<h2>PilotYT</h2>

<div class="container">
    <div class="row">&nbsp;</div>
    <div class="input-group row">
        <span id="songTitleAddon" class="input-group-addon">Tytuł</span>
        <input type="text" readonly class="form-control" id="songTitle" aria-describedby="songTitleAddon" value="">
    </div>
    <div class="input-group row">
        <span id="songArtistAddon" class="input-group-addon">Wykonawca</span>
        <input type="text" readonly class="form-control" id="songArtist" aria-describedby="songArtistAddon" value="">
    </div>
    <div class="input-group row">
        <span id="songAlbumAddon" class="input-group-addon">Album</span>
        <input type="text" readonly class="form-control" id="songAlbum" aria-describedby="songAlbumAddon" value="">
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <div id="player"></div>
    </div>
    @*<div class="row">&nbsp;</div>*@
    <div class="row">
        <div id="songTime" class="pull-right"></div>
    </div>
    <div class="row">
        <div class="progress">
            <div id="songProgress" class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                <span class="sr-only">45% Complete</span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <button id="mediaButton" class="btn btn-default"><i class="fa fa-music"></i></button>
            <button id="playButton" class="btn btn-default"><i class="fa fa-play"></i> / <i class="fa fa-pause"></i></button>
            <button id="prevButton" class="btn btn-default"><i class="fa fa-backward"></i></button>
            <button id="nextButton" class="btn btn-default"><i class="fa fa-forward"></i></button>
            <button id="stopButton" class="btn btn-default"><i class="fa fa-stop"></i></button>
            <button id="infoButton" class="btn btn-default"><i class="glyphicon glyphicon-refresh"></i></button>

        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/pilotYT.js"></script>
    <script src="https://www.youtube.com/iframe_api"></script>
}

Pilot/Views/PilotLocal/Index.cshtml
@{
    ViewData["Title"] = "Pilot medialny";
}

@section DevStyles
{
    <link rel="stylesheet" href="~/css/pilotLocal.css" />
}

@section Scripts {
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/pilotLocal.js"></script>
}

<div class="container">
    <div class="row">&nbsp;</div>
    <div class="col-sm-12 col-md-4 col-lg-3">
        <img id="songImage" class="media-object song-cover" src="" />
        <div id="karaokeBox" class="karaoke">
        </div>
        <div class="row">&nbsp;</div>
    </div>
    <div class="col-sm-12 col-md-8 col-lg-9">
        <div class="input-group row">
            <span id="songTrackAddon" class="input-group-addon">Ścieżka</span>
            <input type="text" readonly class="form-control" id="songTrack" aria-describedby="songTrackAddon" value="">
        </div>
        <div class="input-group row">
            <span id="songTitleAddon" class="input-group-addon">Tytuł</span>
            <input type="text" readonly class="form-control" id="songTitle" aria-describedby="songTitleAddon" value="">
        </div>
        <div class="input-group row">
            <span id="songArtistAddon" class="input-group-addon">Wykonawca</span>
            <input type="text" readonly class="form-control" id="songArtist" aria-describedby="songArtistAddon" value="">
        </div>
        <div class="input-group row">
            <span id="songAlbumAddon" class="input-group-addon">Album</span>
            <input type="text" readonly class="form-control" id="songAlbum" aria-describedby="songAlbumAddon" value="">
        </div>
        <div class="input-group row">
            <span id="songYearAddon" class="input-group-addon">Rok</span>
            <input type="text" readonly class="form-control" id="songYear" aria-describedby="songYearAddon" value="">
        </div>
        <div class="input-group row">
            <span id="songGenereAddon" class="input-group-addon">Gatunek</span>
            <input type="text" readonly class="form-control" id="songGenere" aria-describedby="songGenereAddon" value="">
        </div>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <div id="songTime" class="pull-right"></div>
    </div>
    <div class="row">
        <div class="progress">
            <div id="songProgress" class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%; transition:2000ms;">
                <span class="sr-only">45% Complete</span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <button id="mediaButton" class="btn btn-default"><i class="fa fa-music"></i></button>
            <button id="playButton" class="btn btn-default"><i class="fa fa-play"></i> / <i class="fa fa-pause"></i></button>
            <button id="prevButton" class="btn btn-default"><i class="fa fa-backward"></i></button>
            <button id="nextButton" class="btn btn-default"><i class="fa fa-forward"></i></button>
            <button id="stopButton" class="btn btn-default"><i class="fa fa-stop"></i></button>
            <button id="infoButton" class="btn btn-default"><i class="glyphicon glyphicon-refresh"></i></button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <img id="qrCodeSiteUrl" class="media-object img-responsive center-block"
                 src="@Url.Action("SiteUrl", "QrCode")" />
        </div>
    </div>
</div>

Pilot/Views/PilotYouTube/Index.cshtml
@{
    ViewData["Title"] = "PilotYT";
}

<h2>PilotYT</h2>

<div class="container">
    <div class="row">&nbsp;</div>
    <div class="input-group row">
        <span id="songTitleAddon" class="input-group-addon">Tytuł</span>
        <input type="text" readonly class="form-control" id="songTitle" aria-describedby="songTitleAddon" value="">
    </div>
    <div class="input-group row">
        <span id="songArtistAddon" class="input-group-addon">Wykonawca</span>
        <input type="text" readonly class="form-control" id="songArtist" aria-describedby="songArtistAddon" value="">
    </div>
    <div class="input-group row">
        <span id="songAlbumAddon" class="input-group-addon">Album</span>
        <input type="text" readonly class="form-control" id="songAlbum" aria-describedby="songAlbumAddon" value="">
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <div id="player"></div>
    </div>
    @*<div class="row">&nbsp;</div>*@
    <div class="row">
        <div id="songTime" class="pull-right"></div>
    </div>
    <div class="row">
        <div class="progress">
            <div id="songProgress" class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                <span class="sr-only">45% Complete</span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <button id="mediaButton" class="btn btn-default"><i class="fa fa-music"></i></button>
            <button id="playButton" class="btn btn-default"><i class="fa fa-play"></i> / <i class="fa fa-pause"></i></button>
            <button id="prevButton" class="btn btn-default"><i class="fa fa-backward"></i></button>
            <button id="nextButton" class="btn btn-default"><i class="fa fa-forward"></i></button>
            <button id="stopButton" class="btn btn-default"><i class="fa fa-stop"></i></button>
            <button id="infoButton" class="btn btn-default"><i class="glyphicon glyphicon-refresh"></i></button>

        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/pilotYT.js"></script>
    <script src="https://www.youtube.com/iframe_api"></script>
}

Pilot/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pilot</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        @RenderSection("DevStyles", required: false)
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" asp-append-version="true" />
        @RenderSection("DevStyles", required: false)
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Pilot</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="PilotYT">Pilot YT</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    @*<partial name="_CookieConsentPartial" />*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Przemysław Mućka</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>